spring:
  application:
    name: reservation
  datasource:
    driver-class-name: org.postgresql.Driver   #postgresql
#    driver-class-name: com.mysql.cj.jdbc.Driver #mysql
    url: jdbc:postgresql://database-1.cjepiro9oz6u.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace
    username: postgres
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true
 #   open-in-view : true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
     # listener 재시도 횟수 설정
    # https://minholee93.tistory.com/entry/RabbitMQ-Retry-Mechanism-with-Spring-Boot
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2
    # rabbitmq 서버주소
    addresses: amqps://b-f96775a8-8bcb-4e8f-a88d-f5e27cb54f03.mq.ap-northeast-2.amazonaws.com:5671 #공동주소
    username: rabbitmq
    password: password123!

        
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
    # service registry 주소 공동으로 만든 주소
      defaultZone: http://ec2-13-125-152-179.ap-northeast-2.compute.amazonaws.com:8761/eureka/
  instance:
  # 본인이 원래 돌리고 있던 인스턴스 주소 한 사람당 1.2.3 다 하는 건지/맡은 번호만 하는 건지 
    hostname: ec2-52-79-254-140.ap-northeast-2.compute.amazonaws.com
management:
  endpoints:
    web:
      exposure:
        include: "*"
