server:
  port: 5050

spring:
  rabbitmq:
#    host: ec2-3-35-229-119.ap-northeast-2.compute.amazonaws.com
#    host: ec2-3-36-116-55.ap-northeast-2.compute.amazonaws.com
    addresses: amqps://b-c39315bb-3511-4197-b9e6-4a17aed773d7.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123